default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>

development:
  <<: *default
  database: anamnese_albrea_development
  host: 127.0.0.1
  username: albrea
  password: albrea123

test:
  <<: *default
  database: anamnese_albrea_test
  host: 127.0.0.1
  username: albrea
  password: albrea123

production:
  <<: *default
  database: <%= ENV["DB_NAME"] %>
  host: <%= ENV["DB_HOST"] %>
  port: <%= ENV.fetch("DB_PORT", 5432) %>
  username: <%= ENV["DB_USER"] %>
  password: <%= ENV["DB_PASSWORD"] %>